# Generated by Django 2.2.7 on 2020-02-20 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='title',
            field=models.CharField(blank=True, db_column='title', max_length=255, null=True),
        ),
    ]
