# Generated by Django 2.2.7 on 2019-11-19 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20191115_1913'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('is_deleted', models.BooleanField(db_column='is_deleted', db_index=True, default=False)),
                ('created_by', models.IntegerField(blank=True, db_column='created_by', null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='created_date', null=True)),
                ('updated_by', models.IntegerField(blank=True, db_column='updated_by', null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, db_column='updated_date', null=True)),
                ('title', models.CharField(db_column='title', max_length=255)),
            ],
            options={
                'verbose_name': 'Type',
                'verbose_name_plural': 'Types',
                'db_table': 'type_master',
            },
        ),
    ]
