# Generated by Django 2.2.7 on 2019-11-19 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(db_column='image', null=True, upload_to='img/product'),
        ),
    ]
