# Generated by Django 2.2.7 on 2019-11-29 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20191127_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.FloatField(db_column='price', default=0.0),
        ),
    ]
