# Generated by Django 2.2.7 on 2020-02-20 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('is_deleted', models.BooleanField(db_column='is_deleted', db_index=True, default=False)),
                ('created_by', models.IntegerField(blank=True, db_column='created_by', null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='created_date', null=True)),
                ('updated_by', models.IntegerField(blank=True, db_column='updated_by', null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, db_column='updated_date', null=True)),
                ('title', models.CharField(db_column='title', max_length=255)),
                ('key', models.TextField(blank=True, db_column='key', null=True)),
                ('content', models.TextField(blank=True, db_column='content', null=True)),
            ],
            options={
                'verbose_name': 'Cms',
                'verbose_name_plural': 'Cms',
                'db_table': 'cms_master',
            },
        ),
    ]
