# Generated by Django 2.2.7 on 2019-12-16 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('is_deleted', models.BooleanField(db_column='is_deleted', db_index=True, default=False)),
                ('created_by', models.IntegerField(blank=True, db_column='created_by', null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='created_date', null=True)),
                ('updated_by', models.IntegerField(blank=True, db_column='updated_by', null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, db_column='updated_date', null=True)),
                ('name', models.CharField(db_column='name', max_length=15)),
            ],
            options={
                'verbose_name': 'AppModel',
                'verbose_name_plural': 'AppModels',
                'db_table': 'app_model',
            },
        ),
        migrations.CreateModel(
            name='AppModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('is_deleted', models.BooleanField(db_column='is_deleted', db_index=True, default=False)),
                ('created_by', models.IntegerField(blank=True, db_column='created_by', null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='created_date', null=True)),
                ('updated_by', models.IntegerField(blank=True, db_column='updated_by', null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, db_column='updated_date', null=True)),
                ('name', models.CharField(db_column='name', max_length=15, unique=True)),
            ],
            options={
                'verbose_name': 'AppModule',
                'verbose_name_plural': 'AppModules',
                'db_table': 'app_module',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('is_deleted', models.BooleanField(db_column='is_deleted', db_index=True, default=False)),
                ('created_by', models.IntegerField(blank=True, db_column='created_by', null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='created_date', null=True)),
                ('updated_by', models.IntegerField(blank=True, db_column='updated_by', null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, db_column='updated_date', null=True)),
                ('name', models.CharField(db_column='name', max_length=15)),
                ('code', models.CharField(db_column='code', max_length=15)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_model', to='role_permission.AppModel')),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
                'db_table': 'permission_master',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('is_deleted', models.BooleanField(db_column='is_deleted', db_index=True, default=False)),
                ('created_by', models.IntegerField(blank=True, db_column='created_by', null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='created_date', null=True)),
                ('updated_by', models.IntegerField(blank=True, db_column='updated_by', null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, db_column='updated_date', null=True)),
                ('name', models.CharField(db_column='name', max_length=15)),
                ('company_id', models.IntegerField(blank=True, db_column='company_id', null=True)),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'db_table': 'role_master',
            },
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('is_deleted', models.BooleanField(db_column='is_deleted', db_index=True, default=False)),
                ('created_by', models.IntegerField(blank=True, db_column='created_by', null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='created_date', null=True)),
                ('updated_by', models.IntegerField(blank=True, db_column='updated_by', null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, db_column='updated_date', null=True)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_permission_permission', to='role_permission.Permission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_permission_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'UserPermission',
                'verbose_name_plural': 'UserPermissions',
                'db_table': 'user_permission',
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('is_deleted', models.BooleanField(db_column='is_deleted', db_index=True, default=False)),
                ('created_by', models.IntegerField(blank=True, db_column='created_by', null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='created_date', null=True)),
                ('updated_by', models.IntegerField(blank=True, db_column='updated_by', null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, db_column='updated_date', null=True)),
                ('company_id', models.IntegerField(blank=True, db_column='company_id', null=True)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permission_permission', to='role_permission.Permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permission_role', to='role_permission.Role')),
            ],
            options={
                'verbose_name': 'RolePermission',
                'verbose_name_plural': 'RolePermissions',
                'db_table': 'role_permission',
            },
        ),
        migrations.AddField(
            model_name='appmodel',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_model_module', to='role_permission.AppModule'),
        ),
        migrations.AlterUniqueTogether(
            name='appmodel',
            unique_together={('name', 'module')},
        ),
    ]
