# Generated by Django 2.2.7 on 2019-12-29 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role_permission', '0002_auto_20191216_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='order_no',
            field=models.IntegerField(db_column='order_no', default=0),
        ),
    ]
