# Generated by Django 2.2.7 on 2019-11-20 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('is_deleted', models.BooleanField(db_column='is_deleted', db_index=True, default=False)),
                ('created_by', models.IntegerField(blank=True, db_column='created_by', null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='created_date', null=True)),
                ('updated_by', models.IntegerField(blank=True, db_column='updated_by', null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, db_column='updated_date', null=True)),
                ('task', models.CharField(db_column='task', max_length=255)),
                ('status', models.IntegerField(db_column='status', default=2)),
                ('issue_date', models.DateTimeField(blank=True, db_column='issue_date', null=True)),
                ('due_date', models.DateTimeField(blank=True, db_column='due_date', null=True)),
                ('assignee', models.ForeignKey(blank=True, db_column='importing_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_assignee', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'db_table': 'task_master',
            },
        ),
    ]
