# Generated by Django 2.2.7 on 2020-03-10 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('is_deleted', models.BooleanField(db_column='is_deleted', db_index=True, default=False)),
                ('created_by', models.IntegerField(blank=True, db_column='created_by', null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='created_date', null=True)),
                ('updated_by', models.IntegerField(blank=True, db_column='updated_by', null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, db_column='updated_date', null=True)),
                ('image', models.ImageField(db_column='image', null=True, upload_to='img/site')),
                ('title', models.CharField(db_column='title', max_length=255)),
                ('image_type', models.CharField(blank=True, db_column='image_type', max_length=255, null=True)),
                ('image_key', models.CharField(blank=True, db_column='image_key', max_length=255, null=True)),
                ('image_link', models.CharField(blank=True, db_column='image_link', max_length=255, null=True)),
                ('description', models.TextField(blank=True, db_column='description', null=True)),
            ],
            options={
                'verbose_name': 'SiteImage',
                'verbose_name_plural': 'SiteImages',
                'db_table': 'site_image_master',
            },
        ),
    ]
