# Generated by Django 2.2.7 on 2020-02-06 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('is_deleted', models.BooleanField(db_column='is_deleted', db_index=True, default=False)),
                ('created_by', models.IntegerField(blank=True, db_column='created_by', null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='created_date', null=True)),
                ('updated_by', models.IntegerField(blank=True, db_column='updated_by', null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, db_column='updated_date', null=True)),
                ('app_name', models.CharField(db_column='app_name', max_length=255)),
                ('logo', models.ImageField(db_column='image', null=True, upload_to='img/company')),
                ('description', models.TextField(blank=True, db_column='description', null=True)),
                ('currency', models.CharField(db_column='currency', max_length=10)),
                ('page_size', models.IntegerField(db_column='page_size', default=10)),
                ('facebook_link', models.CharField(db_column='facebook_link', max_length=255)),
                ('twitter_link', models.CharField(db_column='twitter_link', max_length=255)),
                ('youtube_link', models.CharField(db_column='youtube_link', max_length=255)),
            ],
            options={
                'verbose_name': 'Configuration',
                'verbose_name_plural': 'Configurations',
                'db_table': 'configuration_master',
            },
        ),
    ]
