# Generated by Django 2.2.7 on 2020-02-13 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuration',
            name='app_name',
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='description',
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='facebook_link',
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='page_size',
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='twitter_link',
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='youtube_link',
        ),
        migrations.AddField(
            model_name='configuration',
            name='code',
            field=models.CharField(blank=True, db_column='code', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='name',
            field=models.CharField(blank=True, db_column='name', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='value',
            field=models.CharField(blank=True, db_column='value', max_length=255, null=True),
        ),
    ]
