# Generated by Django 2.2.7 on 2019-11-18 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default=1, upload_to='img'),
            preserve_default=False,
        ),
    ]
