# Generated by Django 2.2.7 on 2019-11-18 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20191118_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(db_column='image', null=True, upload_to='img'),
        ),
    ]
