# Generated by Django 2.2.7 on 2019-11-19 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20191118_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(db_column='image', null=True, upload_to='user/img'),
        ),
    ]
