# Generated by Django 2.2.7 on 2019-11-19 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20191119_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(db_column='image', null=True, upload_to='img/user'),
        ),
    ]
