# Generated by Django 2.2.7 on 2019-11-20 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20191119_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, db_column='adsress', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateTimeField(blank=True, db_column='date_of_birth', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='id_proof',
            field=models.ImageField(db_column='id_proof', null=True, upload_to='img/id'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(db_column='is_verified', default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_deleted',
            field=models.BooleanField(db_column='is_deleted', db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[(1, 'Admin'), (2, 'Salesman')], db_column='user_type', max_length=2, null=True),
        ),
    ]
