# Generated by Django 2.2.7 on 2019-11-20 17:52

import base.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20191120_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_column='username', default=base.utils.get_unique_id, max_length=100, unique=True),
        ),
    ]
