# Generated by Django 2.2.7 on 2019-11-21 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20191121_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_varified',
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(db_column='is_verified', default=False),
        ),
    ]
