# Generated by Django 2.2.7 on 2019-12-04 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20191121_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, db_column='date_of_birth', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[(1, 'Admin'), (2, 'Salesman'), (3, 'Customer')], db_column='user_type', max_length=2, null=True),
        ),
    ]
