# Generated by Django 2.2.7 on 2019-12-31 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20191207_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='salesman_id',
            field=models.CharField(blank=True, db_column='salesman_id', max_length=10, null=True),
        ),
    ]
